import Header from "@/components/Header.jsx";

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  weight: "variable",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export const metadata = {
//   title: "Next.js Blog",
//   description: "A simple blog built with Next.js",
//   openGraph: {
//     title: "Next.js Blog",
//     description: "A simple blog built with Next.js",
//     type: "website",
//     url: "https://next-comments-postgres.vercel.app/",
// images: ["https://next-comments-postgres.vercel.app/og-image.png"], // add an appropriate image to your public folder - need to be in an array
//   },
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
